services:
  buggregator:
    labels:
      - dev.orbstack.domains=buggregator.josepostiga.local
      - dev.orbstack.http-port=8000
    image: ghcr.io/buggregator/server
    restart: unless-stopped
    expose:
      - 8000
      - 1025
      - 9912
      - 9913
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s

  postgres:
    labels:
      - dev.orbstack.domains=db.josepostiga.local
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s

volumes:
  db-data: